### ISSUE TITLE
Are we sure warnings due to file race conditions are resolved?

### ISSUE THREAD

**Issue by archon810** [android-police/wp-widget-cache#2]

**Comment by SeBsZ** [comment]
The problem here wasn't a race condition (well there might be a race condition, but that's something else completely). The problem here was it never checked the output of fopen, which fails sometimes because a directory isn't there yet. This fix isn't to prevent race or syncing issues between the fopen line and the flock and fput lines - it's to make sure we actually just opened a file. In this function there is no check to see if the file we're about to open is actually going to work or not. The is_writable check above is only to check files that are already there. This fix checks for files that aren't already there.

**Comment by archon810** [comment]
I noticed the issue the most when deletions are rapid firing when dumping trash. My guess is there are lots of race conditions here, actually, and cache gets dumped upon each deletion potentially very frequently.

**Comment by SeBsZ** [comment]
Try this fix first, it'll be interesting to see if the race condition is so extreme that it happens in between these lines - and now we'll hear about it. If I suppress the errors we will never know. I think the race condition originates in another function where it still has to create the directory (or the directory is already deleted) and then it tries to write another cache to it. If that's the case then this fix solves it.

**Comment by archon810** [comment]
Ha https://sentry.io/illogical-robot-llc/apkmirrorcom/issues/207274650/.
